<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/library/jquery.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/library/jquery-ui.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/library/bootstrap.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/library/jquery.sticky.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/library/jquery.jcarousel.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/library/jcarousel.connected-carousels.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/library/owl.carousel.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/library/progressbar.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/library/jquery.bracket.min.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/library/chartist.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/library/Chart.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/library/fancySelect.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/library/isotope.pkgd.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/library/imagesloaded.pkgd.js"></script>

<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/jquery.team-coundown.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/matches-slider.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/header.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/matches_broadcast_listing.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/news-line.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/match_galery.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/main-club-gallery.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/product-slider.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/circle-bar.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/standings.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/shop-price-filter.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/timeseries.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/radar.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/slider.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/preloader.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/diagram.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/bi-polar-diagram.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/label-placement-diagram.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/donut-chart.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/animate-donut.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/advanced-smil.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/svg-path.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/pick-circle.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/horizontal-bar.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/gauge-chart.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/stacked-bar.js"></script>

<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/library/chartist-plugin-legend.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/library/chartist-plugin-threshold.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/library/chartist-plugin-pointlabels.js"></script>

<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/treshold.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/visible.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/anchor.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/landing_carousel.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/landing_sport_standings.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/twitterslider.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/champions.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/landing_mainnews_slider.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/carousel.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/video_slider.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/footer_slides.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/player_test.js"></script>

<script type="text/javascript" src="<?php echo ASSET_PATH; ?>js/main.js"></script>
<script type="text/javascript" src="<?php echo ASSET_PATH; ?>dev-assets/demo-switcher.js"></script>